export const SALE_STATUS = {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    REJECTED: "REJECTED",
};

export const TRANSACTION_TYPE = {
    ADVANCE_CREDIT: "ADVANCE_CREDIT",
    FINAL_CREDIT: "FINAL_CREDIT",
    FINAL_DEBIT: "FINAL_DEBIT",
    WITHDRAWAL: "WITHDRAWAL",
    WITHDRAWAL_REFUND: "WITHDRAWAL_REFUND"
};

export const WITHDRAWAL_STATUS = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
};